### ISSUE TITLE
Class 'CSSmin' not found

### ISSUE THREAD

**Issue by bboyaching** [fisharebest/laravel-assets#10]
It throw error when I add css file
`Class 'CSSmin' not found in .../laravel-assets/src/Filters/MinifyCss.php:37`

I think it will be modified to "use tubalmartin\CssMin\Minifier as CSSmin" in line 22

**Comment by fisharebest** [comment]
There has been a significant change in the mrclay/minify package between versions 3.0.0 and 3.0.1.

I will create a new release that replaces `"mrclay/minify": "~3.0"` with `"mrclay/minify": "3.0.0"`.

Later, I will update the package to work with 3.0.1
