### ISSUE TITLE
Class Assets not found

### ISSUE THREAD

**Issue by dels07** [fisharebest/laravel-assets#12]
Hi,

I already followed installation guide, service provider and aliases already added in config.php.
Already done php artisan optimize, composer dump-autoload, however I still cannot use this on my blade or controller
```php
Assets::add();
nor
\Assets::add();
```
Using Laravel 5.4.

**Comment by fisharebest** [comment]
Did you add the two entries to the list of service providers and facades in `config/app.pgp`?

Your error suggests you could be missing the facade.

**Comment by dels07** [comment]
My bad, likely due to config cache Laravel use compiled services.php. I tried to delete all files in bootstrap/cache now works fine. 

You can close this issue, thanks.

**Comment by fisharebest** [comment]
> My bad

No problem.
