### ISSUE TITLE
Add assests from diffrent folders (none public)

### ISSUE THREAD

**Issue by anbraten** [fisharebest/laravel-assets#14]
Would be greate to have a special option to add files that aren't inside the public folder.

For example I am running a module system and every module has an app/{module}/assetes folder which would be great to access aswell.

**Comment by fisharebest** [comment]
The package has an `enabled` option.  This allows you to disable it during development.  (Who wants to debug minified JS!).

This obviously requires that your asset files are in the public folder.

One workaround is to use an absolute URL for the assets, and create a simple route to serve these from the private folder.  e.g.

1) load the asset using: `Assets::add('http://example.com/module/XXX/assets/style.css`
2) In your routes.php: `Route::get('module/XXX/assets/style.css', function () { return file_get_contents('module/assets/style.css'; });`

The HTTP request would be cached after the first use, so no performance issues with this.

**Comment by anbraten** [comment]
Nice idea.

**Comment by anbraten** [comment]
Using a loadbalancer brings this work around to a new problem. I cannot access the files by url now.
How can I directly access that files?

Can this module detect file chnages, so the assets cache is updated or do I need to use assets:purge every time I am developing my app?

**Comment by fisharebest** [comment]
> Can this module detect file changes

Yes.  It checks the timestamp of the file.  If this changes, we will process the file again.

https://github.com/fisharebest/laravel-assets/blob/master/src/Assets.php#L505-L508

**Comment by fisharebest** [comment]
> I cannot access the files by url now. How can I directly access that files?

I don't understand why a load balancer causes a problem.

Each of your webservers will have all the original asset files.
Each one will generate its own minfified files.

**Comment by anbraten** [comment]
So you reprocess local files, but none with absolute path?!

My load balancer is talking to the webservers by using proxy protocol, so I cant use localhost on my webservers as I did, and the public domain of my site is unknown to the webservers.

Sorry if my setup  (or my description of it ;) ) seems a bit complicated, but I would really love to use your module.

**Comment by fisharebest** [comment]
> so I cant use localhost on my webservers as I did

The module reads from URLs using a Loader.

See https://github.com/fisharebest/laravel-assets/blob/master/src/Loaders/FileGetContents.php

You can easily create and use your own loader.

e.g. something like this:

```
class MyLoader extends \Fisharebest\LaravelAssets\Loaders\FileGetContents {
	public function loadUrl($asset_url) {
		$asset_url = str_replace(
			'http://localhost/',
			'/path/to/my/asset/folder/',
			$asset_url
		);

		return parent::loadUrl($asset_url);
	}
}
```

Specify this loader in the config file.

```
'loader' => new \MyApp\MyLoader,
```

It will convert requests for `http://localhost/foo/bar.js` to `/path/to/my/asset/folder/foo/bar.js`, and leave others untouched.

**Comment by anbraten** [comment]
Okay that is much cleaner and nicer to use for local assets. But still having to deal with updating the cache (artisan assets:purge), because the files are not checked by timestamp?! Any ideas to improve that? I mostly need this for development while building new scripts and styles.

**Comment by fisharebest** [comment]
Assets are based on the timestamp of local files or the URL of remote URLs.
(We assume that remote URLs are CDNs, and are fixed).

But you could add a timestamp to your URL.
`http://localhost/foo/bar.js?t=1510166885`
