### ISSUE TITLE
Logic error on vendor publishing

### ISSUE THREAD

**Issue by f-liva** [fisharebest/laravel-assets#4]
When I launch the command

php artisan vendor:publish --provider="Fisharebest\LaravelAssets\AssetsServiceProvider"

I get this error:

 [LogicException]
 The command defined in "Fisharebest\LaravelAssets\Commands\Purge" cannot ha
 ve an empty name.

The privider and the alias is already added in the config/app.php file.

**Comment by fisharebest** [comment]
While I investigate this, you can simply copy the configuratioon file `.../config/assets.php` to your `/config/` folder.

**Comment by f-liva** [comment]
I resolved declaring a protected $name variable in the Purge class.
However, I have some other problems, I'll write you in the next days

Il giorno lun 1 feb 2016 alle ore 23:41 Greg Roach notifications@github.com ha
scritto:
While I investigate this, you can simply copy the configuratioon file .../config/assets.php to your /config/ folder.

**Comment by fisharebest** [comment]
I have tried adding the package to some other projects, and cannot reproduce your error.

**Comment by f-liva** [comment]
I use you package with Laravel 5.0

Declaring `protected $name = 'assets:purge';` in the Fisharebest\LaravelAssets\Commands\Purge class solves the issue.

**Comment by fisharebest** [comment]
I have added Laravel 5.0 into the build matrix, and added a unit test for `artisan publish`.

Thanks for the bug report.
