### ISSUE TITLE
Non-static method 

### ISSUE THREAD

**Issue by subhasundardass** [fisharebest/laravel-assets#7]
'providers' => [
       Fisharebest\LaravelAssets\AssetsServiceProvider::class,
]

'aliases' => [
      'Assets' => Fisharebest\LaravelAssets\AssetsFacade::class,
]

HomeController
use Fisharebest\LaravelAssets\Assets;

function index(){
     Assets::add(['analytics.js']) ;
}

ErrorException in HomeController.php line 25:
Non-static method Fisharebest\LaravelAssets\Assets::add() should not be called statically, assuming $this from incompatible context

**Comment by fisharebest** [comment]
Remove `use Fisharebest\LaravelAssets\Assets;` (or replace with `use Assets;`).

When you use the facade, you want `\Assets::` - not `\Fisharebest\LaravelAssets\Assets::`

**Comment by subhasundardass** [comment]
Thank you

Subha S Das
