### ISSUE TITLE
Fatal Error in Laravel 5.4

### ISSUE THREAD

**Issue by JamesFreeman** [fisharebest/laravel-assets#8]
Just installed this package with Laravel 5.4 and got the following error:

> FatalErrorException in AssetsServiceProvider.php line 56:
> Call to undefined method Illuminate\Foundation\Application::share()

After some investigation I found the problem was to-do with this code:
```
$this->app->bind('command.assets.purge', $this->app->share(function(Application $app) {
	return new Purge($app->make('assets'));
}));
```
I replaced it with the following code and it seems to work perfectly. 
```
$this->app->bind('command.assets.purge', function(Application $app) {
	return new Purge($app->make('assets'));
});
```

**Comment by fisharebest** [comment]
I can't remember why I used `$this->app->share()`.  Probably just copying example code from the documentation...

I'll test/fix as soon as I can.
